-- MySQL Script generated by MySQL Workbench
-- Tue May  5 12:45:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja_i2hsb_3103
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_i2hsb_3103
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_i2hsb_3103` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `loja_i2hsb_3103` ;

-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(100) NULL DEFAULT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`clientes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(12) NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CPF` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`enderecos` (
  `IdEndereco` INT NOT NULL AUTO_INCREMENT,
  `Cep` VARCHAR(8) NOT NULL,
  `Uf` VARCHAR(2) NOT NULL,
  `Cidade` VARCHAR(100) NOT NULL,
  `Bairro` VARCHAR(100) NULL DEFAULT NULL,
  `Logradouro` VARCHAR(150) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL,
  `Complemento` VARCHAR(100) NULL DEFAULT NULL,
  `IdCliente` INT NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdEndereco`),
  INDEX `fk_enderecos_clientes` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_clientes`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `loja_i2hsb_3103`.`clientes` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`pedidos` (
  `IdPedidos` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NOT NULL,
  `subTotal` DECIMAL(18,2) NOT NULL,
  `status` ENUM('Aberto', 'Finalizado', 'Pendente') NOT NULL,
  `dataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdPedidos`),
  INDEX `fk_clientes_pedidos` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_pedidos`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `loja_i2hsb_3103`.`clientes` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`produtos` (
  `IdProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NULL DEFAULT NULL,
  `valorProduto` DECIMAL(18,2) NULL DEFAULT NULL,
  `idCategoria` INT NULL DEFAULT NULL,
  `vinculoImagem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProduto`),
  INDEX `fk_produtos_categoria` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `loja_i2hsb_3103`.`categorias` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`itens_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`itens_pedidos` (
  `IdItensPedidos` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `IdProduto` INT NOT NULL,
  `quantidade` DECIMAL(18,2) NOT NULL,
  `valorItem` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`IdItensPedidos`),
  INDEX `fk_itens_pedidos_pedidos` (`IdPedido` ASC) VISIBLE,
  INDEX `fk_itens_pedidos_produtos` (`IdProduto` ASC) VISIBLE,
  CONSTRAINT `fk_itens_pedidos_pedidos`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `loja_i2hsb_3103`.`pedidos` (`IdPedidos`),
  CONSTRAINT `fk_itens_pedidos_produtos`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `loja_i2hsb_3103`.`produtos` (`IdProduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loja_i2hsb_3103`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_i2hsb_3103`.`telefones` (
  `IdTelefone` INT NOT NULL AUTO_INCREMENT,
  `Telefone` VARCHAR(20) NOT NULL,
  `IdCliente` INT NOT NULL,
  `DataCad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdTelefone`),
  INDEX `fk_telefones_clientes` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `loja_i2hsb_3103`.`clientes` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
